companieshouse/orders.web.ch.gov.uk

- Makefile
- README.md
- gulpfile.js
- package-lock.json
- package.json
- src/app.ts
- src/handlers/home.ts
- src/handlers/index.ts
- src/routers/index.ts
- src/server.ts
- src/test/handlers/home.spec.ts
- src/test/jest.config.js
- src/test/setup.ts
- src/views/base.html
- src/views/index.html
- static/_variables.scss
- static/app.scss
- tsconfig.json
- tslint.json
This is a copy of node-web-starter.
> Initial commit is a copy of node-web-starter

- tsconfig.json
modified tsconfig
resolved: PC-631
> modified tsconfig

- package-lock.json
- package.json
- src/app.ts
- src/bin/www.ts
- src/middleware/auth.middleware.ts
removed logger
resolves: GCI-1004
> removed logger

- src/views/layout.html
- src/views/order-complete.html
- Implement print functionality following CICs and LFP example
- Ensure print option not present when javascript switched off
Resolves: GCI-940
> Implement print page option for order complete page

- src/test/controllers/order.confirmation.controller.integration.test.ts
fixed unit test
resolves: GCI-553
> Certificate ordered test

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
added missing delivery details
resolves: GCI-553
> added missing delivery details

- src/views/layout.html
- src/views/order-complete.html
fixed return to company overview link
resolves: GCI-553
> fixed return to company overview link

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
- src/views/layout.html
moved swapped county and postcode
resolves: GCI-553
> moved swapped county and postcode

- src/views/layout.html
> add favicon for browser tab

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/views/order-complete.html
added aria-label for order reference
resolves: GCI-1110
> added aria-label for order reference

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
Check undefined for included on certificate.
resolves: GCI-1174
> check undefined for included on certificate

- package-lock.json
- package.json
- src/app.ts
- src/config/config.ts
> bump session handler version to log correct time

- .eslintrc
- package.json
- src/client/api.client.ts
- update linting ruleset to ensure semi-colons are mandatory
- add script to autofix minor linting errors
> chore: update linting rules

- src/views/layout.html
> Add accessibility statement to footer

- src/views/order-complete.html
Modify copy on confirmation page.
> Chore/GCI-1237: Update copy on confirmation page

- src/views/layout.html
> Remove statement until accessibility audit done for service

- src/app.ts
- src/client/api.client.ts
- src/controllers/basket.controller.ts
- src/controllers/error.controller.ts
- src/model/template.paths.ts
- src/test/controllers/basket.controller.integration.test.ts
- src/views/error-not-found.html
- src/views/error-start-again.html
- src/views/error.html
display error when delivery missing
resolves: GCI-1231
> Gci 1231 display error when delivery missing

- src/views/error-not-found.html
- src/views/error-start-again.html
- src/views/error.html
removed service name from header when there is an error message
resolves: GCI-1231
> removed service name from header

- src/config/config.ts
- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/views/layout.html
- src/views/order-complete.html
updated order confirmation controller to handle certified copies
pass variables from the order controller to the template dependent on order type
updated order complete template to handle variables being passed from the controller
updated integration test for order controller
Resolves: GCI-124
> Create skeleton page for certified copy confirmation page

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
update delivery text 
update tests
Resolve: GCI-1245
> update delivery text  and update tests

- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/views/order-complete.html
Amended text to say Your document details instead of Document details
GCI-1353
> Amended text on order confirmation page

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
redirect cancelled or declined payments for certified copies
resolves: GCI-1342
> redirect cancelled or declined payments for certified copies

- .gitmodules
- Makefile
- package-lock.json
add api enumerations sub module to orders web
Resolves GCI-1341
> add api enumerations sub module to orders web

- package-lock.json
- package.json
- src/config/api.enumerations.ts
- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
- src/utils/check.details.utils.ts
- src/views/order-complete.html
bump node sdk dependency
implement usage of api enumerations module
update order confirmation controller to display filing history document details
add unit test
update integration test for order confirmation
add check details utility
update order confirmation view to display selected filing history documents
Resolves: GCI-1340
> display certified copy details on order confirmation page for certs copies

- package-lock.json
- package.json
> Add js yaml and types as dependencies

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
> Add missing image delivery item type parameter to url

- package-lock.json
Versions bumped for `bl` and `lodash`
> Fix for security vulnerabilities

- src/config/config.ts
- src/service/map.item.service.ts
- src/test/service/map.item.service.unit.test.ts
added service url to order confirmation page
resolves: GCI-222
> added service url to order confirmation page

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
> Display error for cancelled/declined payment and return user to check order details page

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
> Remove race condition and update test

- src/controllers/order.confirmation.controller.ts
- src/service/map.item.service.ts
- src/test/__mocks__/order.mocks.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/service/map.item.service.unit.test.ts
add dissolved certificate to map item service
add dissolved certificate to test mocks
add integration test for rendering of dissolved certificate confirmation details
add dissolved certificate to map item service test
resolve linting issue
Resolves: GCI-1422
> Render confirmation page for dissolved certificate details

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
> Add itemType for dissolved certificate

- src/service/map.item.service.ts
Updated text on confirmation page for mid as per prototype
Resolves: GCI-1637
> update text on confirmation page for mid

- src/service/map.item.service.ts
> update text on confirmation page

- package-lock.json
- package.json
- src/app.ts
- src/controllers/basket.controller.ts
- src/controllers/order.confirmation.controller.ts
- src/middleware/auth.middleware.ts
- src/test/__mocks__/redis.mocks.ts
Updated version of ch session handler by importing the npm repo of the ch session handler, no longer using the git repo.
Resolves: BI-6119
> implement npm ch node session handler

- package-lock.json
- package.json
bump node session handler version
Resolves: BI-6119
> bump node session handler version

- src/service/map.item.service.ts
Corrected ID to remove duplicate ID
Jira Ticket : BI-6159
> Corrected ID to remove duplicate ID

- src/service/map.item.service.ts
Corrected missing apostrophe in id value
Jira ticket - BI-6159
> Corrected missing apostrophe in id value

- src/views/order-complete.html
Replaced capital letter for lower case as it was causing test automation failures
> Text formatting change

- src/service/map.item.service.ts
- src/test/__mocks__/order.mocks.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/service/map.item.service.unit.test.ts
> BI-6030 - Update order confirmation screen with register office address options

- package-lock.json
- package.json
- src/client/api.client.ts
- src/controllers/basket.controller.ts
- src/controllers/order.confirmation.controller.ts
- src/service/map.item.service.ts
- src/test/__mocks__/order.mocks.ts
- src/test/client/api.client.unit.test.ts
- src/test/controllers/basket.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
- src/test/service/map.item.service.unit.test.ts
Initial commit of changes for director options
Jira Ticket : BI-6016
> Initial commit of changes for director options

- package-lock.json
- package.json
- src/service/map.item.service.ts
- src/test/service/map.item.service.unit.test.ts
Added changes to display secretary options on confirmation page
Jira Ticket: BI-6221
> Added changes for secretary options on confirmation page

- package-lock.json
- package.json
- src/app.ts
- src/views/components/cookie-consent-banner.html
- src/views/layout.html
Add cookie consent banner to orders web
Resolves: BI-7185
> add cookie consent banner

- src/config/config.ts
- src/service/map.item.service.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/service/map.item.service.unit.test.ts
- src/test/setup.ts
use config dispatch days to output on cert copies confirmation page
update tests
Resolves: BI-7351
> update cert copies confirmation page

- src/service/map.item.service.ts
- src/test/service/map.item.service.unit.test.ts
Further update for cert copies confirmation page to use config dispatch day value
Update test
Resolves: BI-7351
> use dispatch days config value

- src/service/map.item.service.ts
- src/test/service/map.item.service.unit.test.ts
update confirmation page for certs and diss cert to use config dispatch date 
update test
Resolves: BI-7350
> Use dispatch date config on confirmation page for certs

- src/controllers/order.confirmation.controller.ts
- src/views/order-complete.html
> BI-7854 add piwik on printlink

- package.json
- src/service/map.item.service.ts
Added html escape for order confirmation page
Resolved BI-7727
> Added html escape for order confirmation page

- src/controllers/order.confirmation.controller.ts
fix missed spaces in new page titles
Resolves: CHS-2054
> fix missed spaces in new page titles

- src/views/components/footer/template.njk
> update built by ch link

- src/views/components/footer/template.njk
- static/footer.scss
> BI-8876 - Underline copyright link in orders web

- package-lock.json
- package.json
- fixes designated members details mapping
Resolves: [BI-9121 Fix certificate item options mapping](https://companieshouse.atlassian.net/browse/BI-9121)
> BI-9121 Use latest api-sdk-node

- src/service/LLPCertificateItemMapper.ts
- src/service/LPCertificateItemMapper.ts
- Use consistent spelling and grammar for officer details
Resolves [BI-9155 (Incorrect Officer Details Wording - Across LLP and LP journey)](https://companieshouse.atlassian.net/browse/BI-9155)
> BI-9155 Change wording for officer details

- src/test/__mocks__/order.mocks.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
add unit test for retry checkout
> add unit test for retry checkout

- src/config/FeatureFlags.ts
- src/config/config.ts
- src/model/CompanyType.ts
- src/service/ItemMapperFactory.ts
- src/service/ItemMapperFactoryConfig.ts
- src/service/map.item.service.ts
- src/test/__mocks__/order.mocks.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/service/ItemMapperFactory.unit.test.ts
- src/test/service/ItemMapperFactoryConfig.unit.test.ts
- src/test/setup.ts
- Implement LLP and LP journey feature flags 
[BI-9193: Feature Flags for LLP/LP journeys](https://companieshouse.atlassian.net/browse/BI-9193)
> BI-9193 feature flags for llp and lp journeys

- src/views/components/footer/template.njk
- src/views/layout.html
Update contact page link for orders web to be consistent with the orders journey.
Resolves: BI-10588
> BI-10588 - Update Contact page link orders web

- src/config/config.ts
- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
Rework the retry mechanism to ensure that the correct number are retries are attempted with a delay and allow for configurable retry attempts and delays.
Resolves: BI-10669
> BI-10669 - Rework the retry mechanism for missing payment details 

- package-lock.json
- package.json
* Use latest version of api-sdk-node version which include administrator details changes
* Ran unit tests- everything passes
* Regression test order journey- still works
Resolves [BI-9852](https://companieshouse.atlassian.net/browse/BI-9852)
> BI-9852 Upgrade api-sdk-node version

- package-lock.json
- package.json
- src/config/FeatureFlags.ts
- src/config/config.ts
- src/model/CompanyStatus.ts
- src/service/AdministratedLLPCertificateItemMapper.ts
- src/service/AdministratedOtherCertificateItemMapper.ts
- src/service/ItemMapperFactoryConfig.ts
- src/test/service/AdministratedLLPCertificateItemMapper.unit.test.ts
- src/test/service/AdministratedOtherCertificateItemMapper.unit.test.ts
- src/test/service/ItemMapperFactoryConfig.unit.test.ts
* Extend ItemMapper factory method pattern; create new implementations
for LLP, other company types in administration.
Resolves:
[BI-8857](https://companieshouse.atlassian.net/browse/BI-8857)
> BI-8857 Implement view model for administrated certs

- Makefile
- package-lock.json
- package.json
- sonar-project.properties
> Adding sonar.

- sonar-project.properties
Change test directory for sonar.
> Change test directory for sonar

- src/service/map.item.service.ts
BI-11225-Update order confirmation page for certificates -same day option/email selection/fee (Dissolved companies)
> Update order confirmation page for certificates -same day option/email selection/fee (Dissolved companies)

- routes.yaml
* Register /delivery-details with haproxy web load balancer.
> GCI-2146 Expose delivery-details endpoint

- src/service/ItemMapper.ts
Remove LLP type from check to enable include email section.
Resolves: BI-11262
> BI-11262 - Update LLP companies to include email section

- src/test/utils/request.util.unit.test.ts
* Fix failing unit test for path check.
> Fix failing unit test

- src/controllers/delivery.details.controller.ts
- src/test/controllers/delivery.details.controller.integration.test.ts
- src/views/delivery-details.html
* Rework button and title text for delivery details page to correspond with basket changes
* Remove backLink const and replace with history.back for backward navigation
> GCI-2170 Change button and heading text for delivery details

- src/service/AdministratedLLPCertificateItemMapper.ts
- src/service/ItemMapper.ts
- src/service/LLPCertificateItemMapper.ts
- src/service/LPCertificateItemMapper.ts
- src/service/LiquidatedLLPCertificateItemMapper.ts
Fix alignment issues by removing redundant actions from order confirmation screen.
> Fix order confirmation alignment issues

- src/mappers/BasketDetailsViewModel.ts
- src/mappers/BasketItemsMapper.ts
- src/test/controllers/basket.controller.integration.test.ts
- src/test/mappers/BasketItemsMapper.unit.test.ts
- src/views/basket.html
* Basket page will now display an empty basket message if user hasn't
added any items.
> GCI-2146 Handle empty basket

- src/mappers/ItemVisitor.ts
- src/test/controllers/basket.controller.integration.test.ts
- src/test/mappers/BasketItemsMapper.unit.test.ts
* View/Change certificate options link on basket page now refers to
view/change cert options page implemented in
certificates.orders.web.ch.gov.uk.
> GCI-2148 Render link to view/change cert options page

- Dockerfile
- package-lock.json
- package.json
- src/app.ts
- src/client/api.client.ts
- src/controllers/basket.controller.ts
- src/mappers/ItemVisitor.ts
- src/model/page.urls.ts
- src/routers/index.ts
- src/test/client/api.client.unit.test.ts
- src/test/controllers/basket.controller.integration.test.ts
- src/test/mappers/BasketItemsMapper.unit.test.ts
- static/app.scss
* Adds a remove link to each item in the users basket
[GCI-2180](https://companieshouse.atlassian.net/browse/GCI-2180)
> GCI-2180 Add remove item link to basket page

- src/service/ItemMapper.ts
- src/service/map.item.service.ts
- src/test/service/map.item.service.unit.test.ts
- src/views/order-complete.html
- Enable same day orders on order confirmation screen for certified copies
- Refactor code
Resolves: BI-11333
> BI-11333 - Update certified copies confirmation to enable same day orders

- src/app.ts
- src/client/api.client.ts
- src/model/page.urls.ts
- src/model/template.paths.ts
- src/order_summary/OrderSummary.ts
- src/order_summary/OrderSummaryController.ts
- src/order_summary/OrderSummaryConverter.ts
- src/order_summary/OrderSummaryDirector.ts
- src/order_summary/OrderSummaryService.ts
- src/routers/index.ts
- src/test/__mocks__/order.mocks.ts
- src/test/client/api.client.unit.test.ts
- src/test/order_summary/OrderSummaryController.integration.test.ts
- src/test/order_summary/OrderSummaryService.unit.test.ts
- src/test/utils/request.util.unit.test.ts
- src/utils/request.util.ts
- src/views/error-unauthorised.html
- src/views/includes/navbar.html
- src/views/order-summary.html
- static/app.scss
* Summary service implemented using builder pattern to build complex
object (summary) in a stepwise way.
> GCI-2195 Implement order summary service

- src/govuk/GovUkSummaryList.ts
- src/order_item_summary/GovUkOrderItemSummaryView.ts
- src/order_item_summary/OrderItemMapper.ts
- src/order_item_summary/OrderItemRequest.ts
- src/order_item_summary/OrderItemSummaryController.ts
- src/order_item_summary/OrderItemSummaryFactory.ts
- src/order_item_summary/OrderItemSummaryService.ts
- src/order_item_summary/OrderItemView.ts
- Declare skeleton classes and interfaces for order item summary
[GCI-2267](https://companieshouse.atlassian.net/browse/GCI-2267)
> GCI-2267 Declare skeleton classes and interfaces for order item summary

- src/order_item_summary/OrderItemSummaryController.ts
- src/test/order_item_summary/OrderItemSummaryController.unit.test.ts
* OrderSummaryController handles an incoming request with session data
attached and fetches order item from associated
OrderItemSummaryService instance.
Resolves:
[GCI-2270](https://companieshouse.atlassian.net/browse/GCI-2270)
> GCI-2270 Implement OrderSummaryController

- src/govuk/GovUkSummaryList.ts
- src/model/template.paths.ts
- src/order_item_summary/GovUkOrderItemSummaryView.ts
- src/order_item_summary/MapperRequest.ts
- src/order_item_summary/MissingImageDeliveryMapper.ts
- src/order_item_summary/NullOrderItemMapper.ts
- src/order_item_summary/OrderItemMapper.ts
- src/order_item_summary/OrderItemSummaryFactory.ts
- src/order_item_summary/OrderItemSummaryService.ts
- src/test/__mocks__/order.mocks.ts
- src/test/order_item_summary/MissingImageDeliveryMapper.unit.test.ts
- src/test/order_item_summary/OrderItemSummaryFactory.unit.test.ts
- src/test/order_item_summary/OrderItemSummaryService.unit.test.ts
- Implement mid mapper
- Implement mapper factory 
[GCI-2268](https://companieshouse.atlassian.net/browse/GCI-2268)
> GCI-2268 Implement missing image delivery mapper and factory

- src/test/order_item_summary/OrderItemSummaryController.integration.test.ts
- src/views/order-item-summary-ccd.html
* Add nav element to template without including navbar (allows the back link to work properly)
* Tested locally, everything works as expected
Resolves [GCI-2275](https://companieshouse.atlassian.net/browse/GCI-2275)
> GCI-2275 Implement certified copy item summary template

- src/order_item_summary/LLPCertificateMapper.ts
- src/order_item_summary/OrderItemSummaryFactory.ts
- src/test/__mocks__/order.mocks.ts
- src/test/order_item_summary/LLPCertificateMapper.unit.test.ts
- src/test/order_item_summary/OrderItemSummaryFactory.unit.test.ts
* Implement LLP certificate mapper for order item summary page.
> GCI-2278 Implement LLP certificate mapper

- src/order_item_summary/LPCertificateMapper.ts
- src/order_item_summary/OrderItemSummaryFactory.ts
- src/test/__mocks__/order.mocks.ts
- src/test/order_item_summary/LPCertificateMapper.unit.test.ts
- src/test/order_item_summary/OrderItemSummaryFactory.unit.test.ts
* Implement summary mapper for limited partnership certificate order
summary page.
> GCI-2279 Implement LP cert summary mapper

- src/model/template.paths.ts
- src/order_item_summary/AbstractCertificateMapper.ts
- src/test/order_item_summary/LLPCertificateMapper.unit.test.ts
- src/test/order_item_summary/LPCertificateMapper.unit.test.ts
- src/test/order_item_summary/OrderItemSummaryController.integration.test.ts
- src/test/order_item_summary/OtherCompanyTypesCertificateMapper.unit.test.ts
- src/views/order-item-summary-certificate.html
* Certificate item summary template extends MID summary template.
* Implement integration test cases for all valid company types, all
valid company statuses.
> GCI-2280 Implement certificate item summary template

- package-lock.json
- package.json
- src/service/MapUtil.ts
- src/test/service/MapUtil.unit.test.ts
Delivery details on the confirmation page will now display the optional company name 
Resolves: BI-11578
> add company name to delivery details 

- src/service/MapUtil.ts
- src/test/service/MapUtil.unit.test.ts
Update positioning for order confirmation and order detail page
Resolves: BI-11801
> BI-11801 - Update company name position in orders web

- package-lock.json
- package.json
- src/client/api.client.ts
- src/test/client/api.client.unit.test.ts
* Use custom order error response in api client getOrder function
[GCI-2286](https://companieshouse.atlassian.net/browse/GCI-2286)
> GCI-2286 Use custom order error response

- src/views/basket.html
* Change label to `Total`.
* Use `govuk-heading-l` to align with prototype font.
* Move the dispatch info and total rows out of and down below the summary list to align layout with prototype.
> BI-11879: Align total section of shopping basket with prototype

- src/views/basket.html
- static/app.scss
> Update order more link to be an add another document button

- src/views/basket.html
> BI-11958 - Ensure delivery details does not show when only mid orders present

- src/views/basket.html
Amendments to add text to speech for empty table headers on basket page
BI-11873
> Amendments to add text to speech for empty table headers on basket page

- src/mappers/ItemVisitor.ts
- src/test/mappers/BasketItemsMapper.unit.test.ts
BI-11872 - Add "hidden text" to remove/view change links on CHS Shopping basket
> Added hidden text for visually impaired user and also unit tests

- src/mappers/ItemVisitor.ts
- src/test/mappers/BasketItemsMapper.unit.test.ts
Amended text for screen readers for certificates view/change and remove links
BI-12014
> Amended text for screen readers for certificates links

- src/mappers/ItemVisitor.ts
- src/test/mappers/BasketItemsMapper.unit.test.ts
Amendments to text to speech for remove certificate links
BI-12014
> Amendments to text to speech for remove certificate links

- src/app.ts
- src/mappers/ItemVisitor.ts
- src/test/mappers/BasketItemsMapper.unit.test.ts
- src/test/mappers/ItemVisitor.unit.test.ts
- src/views/basket.html
- src/views/layout.html
- static/responsive-table.scss
* Restyle continue to payment button for better layout on mobiles.
* Use GOV UK grid system for better page margins.
* Make tables responsive as was done for the dissolved search results table.
> BI-12016: Basket page mobile fixes

- src/config/config.ts
- src/controllers/basket.controller.ts
- src/controllers/delivery.details.controller.ts
- src/test/__mocks__/redis.mocks.ts
- src/test/utils/basket.util.test.ts
- src/utils/basket.util.ts
- src/views/components/user-nav-bar.html
> Add basket link to delivery details and basket page

- src/views/basket.html
BI-12005 - edit delivery text on the basket screen
> changed the delivery details text

- src/controllers/ConfirmationTemplateMapper.ts
- src/controllers/OrderSummaryTemplateMapper.ts
- src/controllers/order.confirmation.controller.ts
- src/test/controllers/OrderSummaryTemplateMapper.unit.test.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/utils/basket.util.test.ts
> Basket link order confirmation

- src/views/error.html
BI-12072 - Certificate Ordering Service Error Message
> Error message and contact us link added across ordering service journeys

- src/app.ts
- src/config/config.ts
- src/controllers/basket.controller.ts
- src/test/controllers/basket.controller.integration.test.ts
- src/test/utils/basket.util.test.ts
- src/views/basket.html
> BI-12169 - Update basket for deliverables being present without a delivery address

- src/config/config.ts
- src/controllers/basket.controller.ts
- src/model/BasketLimit.ts
- src/test/setup.ts
- src/test/utils/basket.util.test.ts
- src/utils/basket.util.ts
- src/views/basket.html
BI-12137 - Shopping Basket basket limit warning
> Bi 12137 basket limit warning

- src/views/basket.html
BI-12137 - Update to warning text and format
> Updated warning text and format

- .gitignore
- .nycrc.json
- Makefile
- package-lock.json
- package.json
- sonar-project.properties
> GCI-2131 - Implement sonar in orders web

- src/app.ts
BI-11974 - add feedback source for the feedback link on basket page
> add feedback source for the feedback link

- src/app.ts
- src/config/config.ts
- src/views/components/footer/template.njk
BI-11793 Added different url for the order journey pages
> Added different url for the order journey pages

- src/app.ts
- src/controllers/ConfirmationTemplateMapper.ts
- src/controllers/OrderSummaryTemplateMapper.ts
- src/controllers/basket.controller.ts
- src/controllers/delivery.details.controller.ts
- src/controllers/order.confirmation.controller.ts
- src/model/PageHeader.ts
- src/test/controllers/OrderSummaryTemplateMapper.unit.test.ts
- src/test/utils/page.header.utils.test.ts
- src/utils/page.header.utils.ts
- src/views/components/user-nav-bar.html
* Use the same approach as is used in `certificates.orders.web.ch.gov.uk`.
> GCI-2426: Fix orders pages multiple sign-in issue

- src/controllers/ConfirmationTemplateMapper.ts
- src/controllers/OrderSummaryTemplateMapper.ts
- src/controllers/order.confirmation.controller.ts
- src/test/controllers/OrderSummaryTemplateMapper.unit.test.ts
- src/test/utils/page.header.utils.test.ts
* Investigation of bug prompted a rationalisation of approach to getting basket and page header state.
> GCI-2431: Fix bug whereby non basket user appears signed out on confirmation page

- src/order_item_summary/OrderItemSummaryController.ts
- src/order_summary/OrderSummaryController.ts
- src/test/order_item_summary/OrderItemSummaryController.unit.test.ts
GCI-2432 Display sign in/sign out bar on order summary page and ordered item details page
[GCI-2432]: https://companieshouse.atlassian.net/browse/GCI-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Display sign in/sign out bar on order summary page and ordered item details page

- src/controllers/error.controller.ts
- src/test/order_item_summary/OrderItemSummaryController.integration.test.ts
- src/test/order_summary/OrderSummaryController.integration.test.ts
BI-12241 - Change error message from 'page not found' to 'Sorry there is a problem'.
> Add error message to Order summary page to match story

- src/controllers/basket.controller.ts
- src/controllers/error.controller.ts
- src/routers/index.ts
- src/test/__mocks__/redis.mocks.ts
- src/test/controllers/basket.controller.integration.test.ts
- src/test/order_item_summary/OrderItemSummaryController.integration.test.ts
- src/test/order_summary/OrderSummaryController.integration.test.ts
- src/test/utils/basket.util.test.ts
- src/test/utils/page.header.utils.test.ts
* Also removed some code that it turns out is no longer used.
> BI-12338: Signin banner incorrect when Orders API down

- src/order_item_summary/OrderItemSummaryController.ts
- src/test/order_item_summary/OrderItemSummaryController.integration.test.ts
- src/test/order_item_summary/OrderItemSummaryController.unit.test.ts
BI-12242 - Display Basket on sign in/sign out bar on ordered item details page
> BI-12242 basket links item details

- src/order_summary/OrderSummaryController.ts
- src/test/order_summary/OrderSummaryController.integration.test.ts
GCI-2438 - Add CHS homepage link to the order summary page of the basket journey
> GCI-2438 add homepage link

- src/controllers/delivery.details.controller.ts
- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
> GCI-2437 - Add find and update header to order confirmation screen

- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
> Cc 482 node 18 upgrade

- terraform/groups/ecs-service/locals.tf
Update the LB path rules to try and encompass all url paths.
> Update LB path rules

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
> Environment vars update

- package-lock.json
> GCI-2521 - Run security audit to fix unsecure dependencies

- .mocharc.json
- src/mappers/ItemVisitor.ts
- src/test/mappers/BasketItemsMapper.unit.test.ts
- src/views/basket.html
Resolves [BI-12024](https://companieshouse.atlassian.net/browse/BI-12024)
Add in quantity column for certificates to support additional copies changes
[BI-12024]: https://companieshouse.atlassian.net/browse/BI-12024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature bi 12024 update basket to display quantity
