companieshouse/orders.web.ch.gov.uk

- package.json
Change `package.json` to link to most recent commit hash for ch-sdk-node.
> Chore/GCI-1279: Update commit hash for ch-sdk-node version

- src/views/order-complete.html
re-added functionality to not display print option if no JS
Resolves GCI-869
> re-added functionality to not display print option if no JS

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
Add a url parameter to allow piwik users to identify what item has been ordered.
Resolves: GCI-1381
> Add itemtype param to order confirmation page

- src/controllers/order.confirmation.controller.ts
- src/service/map.item.service.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
- src/test/service/map.item.service.unit.test.ts
Updated logic to allow user to return to dissolved certs check details page when a payment is cancelled.
Updated service url on confirmation page to return to dissolved certificates start now page
> change url for dissolved certificates

- Tiltfile.dev
Follows the same template as certificates web:
https://github.com/companieshouse/certificates.orders.web.ch.gov.uk/blob/master/Tiltfile.dev
Tested making changes on orders web through docker and it works correctly
> Add tilt file to enable dev through docker on orders web

- src/views/order-complete.html
* Remove warning from confirmation template that user will not receive
a confirmation email as this has now been implemented via new
order-notification-sender service.
Resolves:
[BI-8777](https://companieshouse.atlassian.net/browse/BI-8777)
> BI-8777 Remove notification email warning from template

- src/controllers/order.confirmation.controller.ts
- src/views/components/footer/template.njk
- src/views/error-not-found.html
- src/views/error-start-again.html
- src/views/error.html
- src/views/layout.html
- src/views/order-complete.html
- static/footer.scss
update favicon to govuk crown
update header to to use govuk header
update page titles to match govuk composition
add accessibility link to footer
update footer to show crown copyright
update footer to include Built by companies house with link to ch site
remove css style on footer which was causing alignment issues
Resolves: CHS-2047 CHS-2041 CHS-2037 CHS-2054 BI-8759 BI-8760 BI-8758
> update to gov uk branding

- src/service/LLPCertificateItemMapper.ts
- src/service/LPCertificateItemMapper.ts
- src/service/MapUtil.ts
- src/service/OtherCertificateItemMapper.ts
- src/test/service/MapUtil.unit.test.ts
* Ensure that address details are mapped correctly when they are undefined
Resolves: [BI-9119: TypeError thrown on confirmation page](https://companieshouse.atlassian.net/browse/BI-9119)
> BI-9119 Fix order page confirmation bug when address details option not selected

- package-lock.json
- package.json
- Upgrade to api-sdk-node 1.0.88
Resolves: [BI-9545 Upgrade api-sdk-node version: orders.web.ch.gov.uk](https://companieshouse.atlassian.net/browse/BI-9545)
> BI-9545 Upgrade api-sdk-node dependency

- package-lock.json
- package.json
- Upgrades api-sdk-node to version 1.0.90.
- Tested certificates journey locally, works fine.
[BI-10172](https://companieshouse.atlassian.net/browse/BI-10172)
> BI-10172 - Upgrade api-sdk-node to 1.0.90

- package-lock.json
- package.json
- src/config/FeatureFlags.ts
- src/config/config.ts
- src/model/CompanyStatus.ts
- src/service/ItemMapperFactory.ts
- src/service/ItemMapperFactoryConfig.ts
- src/service/LPCertificateItemMapper.ts
- src/service/LiquidatedLLPCertificateItemMapper.ts
- src/service/LiquidatedOtherCertificateItemMapper.ts
- src/service/MapUtil.ts
- src/service/NullItemMapper.ts
- src/service/OtherCertificateItemMapper.ts
- src/service/map.item.service.ts
- src/test/service/ItemMapperFactory.unit.test.ts
- src/test/service/ItemMapperFactoryConfig.unit.test.ts
- src/test/service/LLPCertificateItemMapper.unit.test.ts
- src/test/service/LPCertificateItemMapper.unit.test.ts
- src/test/service/LiquidatedLLPCertificateItemMapper.unit.test.ts
- src/test/service/LiquidatedOtherCertificateItemMapper.unit.test.ts
- src/test/service/MapUtil.unit.test.ts
- src/test/service/NullItemMapper.unit.test.ts
- src/test/service/OtherCertificateItemMapper.unit.test.ts
* Mappers transform liquidated company certificate items into tables.
* Functionality toggleable with feature flag CERTS_FOR_LIQUIDATED_COMPANIES.
Resolves:
[BI-8850](https://companieshouse.atlassian.net/browse/BI-8850)
> BI-8850 Implement mapper for liquidated company certs

- src/service/MapUtil.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/service/MapUtil.unit.test.ts
* Make line spacing consistent in certififed certs for standard
companies and LLPs' appointments'/members' details.
> Add extra line break to LLP member details confirm

- src/middleware/auth.middleware.ts
- Another attempt to see whether we can convince SonarQube that the redirect URLs used are safe.
- This time we try to do so by looking up a corresponding value for each value obtained from the request, rather than using the value obtained from the request directly.
> GCI-2127: Look up return to URL, rather than get it raw from request

- src/utils/request.util.ts
* User will no longer be presented with an error if they navigate to
/delivery-details if they are unauthenticated.
> GCI-2146 Permit redirection to delivery details handler

- src/service/ItemMapper.ts
- src/test/__mocks__/order.mocks.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
remove logic blocking email copy section for LP companies 
update tests for email copy output - covers lp, llp and dissolved orders
Resolves: BI-11290
> display email copy section for cert orders of LP companies

- package-lock.json
- package.json
- src/controllers/ConfirmationTemplateFactory.ts
- src/controllers/ConfirmationTemplateMapper.ts
- src/controllers/OrderSummaryTemplateMapper.ts
- src/controllers/SingleItemTemplateMapper.ts
- src/controllers/order.confirmation.controller.ts
- src/model/template.paths.ts
- src/service/MapUtil.ts
- src/test/controllers/ConfirmationTemplateFactory.unit.test.ts
- src/test/controllers/ConfirmationTemplateMapper.unit.test.ts
- src/test/controllers/OrderSummaryTemplateMapper.unit.test.ts
- src/test/controllers/SingleItemTemplateMapper.unit.test.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
- src/test/setup.ts
- src/views/order-complete-abbreviated.html
* Abbreviated order summary page displayed for users enrolled for multi
item basket.
* Implement new template for abbreviated order summary page.
* User agent redirected to /basket if payment cancelled/failed and user
enrolled for multi-item basket.
* Fragments of text on new summary page conditionally rendered
based on product classes ordered.
* Fix undefined behaviour if checkout API polling fails.
Resolves:
[GCI-2149](https://companieshouse.atlassian.net/browse/GCI-2149)
> GCI-2149 Implement abbreviated order confirmation page

- src/app.ts
- src/model/page.urls.ts
- src/model/template.paths.ts
- src/order_summary/OrderSummary.ts
- src/order_summary/OrderSummaryController.ts
- src/order_summary/OrderSummaryConverter.ts
- src/order_summary/OrderSummaryService.ts
- src/routers/index.ts
- src/test/order_summary/OrderSummaryController.integration.test.ts
- src/test/order_summary/OrderSummaryService.unit.test.ts
- src/test/utils/request.util.unit.test.ts
- src/utils/request.util.ts
- src/views/error-unauthorised.html
- src/views/includes/navbar.html
- src/views/order-summary.html
- static/app.scss
* Change mapping logic in OrderSummaryConverter to map Order to GovUK
models.
* Implement OrderSummaryController - if order successfully retrieved
then render order details. If response code is HTTP 401 Unauthorized
then render Unauthorized page. Else - render service unavailable.
* Implement template for order summary page.
> GCI-2195 Integrate order summary mapper with order summary controller

- package-lock.json
- package.json
- src/client/api.client.ts
- src/order_item_summary/OrderItemSummaryService.ts
- src/test/client/api.client.unit.test.ts
- src/test/order_item_summary/OrderItemSummaryService.unit.test.ts
* OrderItemSummaryService responsible for fetching order item resource
from orders.api.ch.gov.uk and mapping it to an OrderItemView via the
mapper instance returned by OrderItemSummaryFactory.
* Note: api-sdk-node needs to be rebuilt & api-sdk-node dependency needs
to be updated prior to merging this in.
Resolves:
[GCI-2271](https://companieshouse.atlassian.net/browse/GCI-2271)
> GCI-2271 Implement OrderItemSummaryService

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
* The itemType query param is used to identify which product class a
disenrolled user has ordered in Matomo.
> GCI-2272 Re-add itemType query param to confirmation page

- src/utils/request.util.ts
Add url for orderable item to whitelist, without this when a user signs out on the confirmation page and signs back in they are taken to the order summary page rather than returned back to the confirmation page.
Resolves: GCI-2281 BI-11696
> add url to whitelist for orderable item

- package-lock.json
- package.json
- src/client/api.client.ts
- src/test/client/api.client.unit.test.ts
* GetOrderItem client method now throws InternalServerError if no error
message returned by getOrderItem endpoint.
Related:
https://github.com/companieshouse/api-sdk-node/pull/451
> Raise InternalServerError if no error message

- src/client/api.client.ts
- src/test/client/api.client.unit.test.ts
* API client now throws InternalServerError if HTTP 404 Not Found
returned by getOrderItem endpoint and no message property in response
body.
> Throw InternalServerError if 404 and no error

- src/app.ts
- src/controllers/error.controller.ts
- src/views/error.html
The whole error object was being displayed on the error page, the name of the error is now showing.
The error page also now displays the title in the banner and links to the chs homepage
Resolves: BI-11754
> make error page user friendly

- src/client/api.client.ts
- src/test/client/api.client.unit.test.ts
* When orders.api is down then HTTP 404 and no errors returned by the getOrder endpoint so
* an internal server error is thrown
[GCI-2286](https://companieshouse.atlassian.net/browse/GCI-2286)
> GCI-2286 Throw internal server error getOrder endpoint

- src/views/basket.html
**NOTE** I am afraid the GitHub diff is misleading. For example, it seems to suggest we have changed a table ID from `find-company-button` to `missing-image-delivery-table`. This is certainly **NOT** the case. Confusion may be triggered by a necessary indentation change?
1. Removed a wrapping `div` with a styling class that meant page content would only occupy 2/3 of the width of the page.
2. Applied a style to the certified documents description column to make it wider when space is available to do so.
> BI-11880: Update shopping basket

- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
Correct the URL to matomo to enable capturing of user interactions for orders web pages.
> Update the live matomo url for orders

- src/controllers/order.confirmation.controller.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.unit.test.ts
This appends the itemTypes found on the confirmation page of an enrolled baskets confirmation page.
This enabled the Matomo CDN file to then use that value to send it to the Matomo analytics to track each type of the itemTypes.
They can be one of four values:
'certificate': 1,
'certified-copy': 2,
'missing-image-delivery': 3,
'dissolution': 4
> BI-13684: Append itemTypes url parameter on enrolled confirmation

- src/order_item_summary/AbstractCertificateMapper.ts
- src/test/__mocks__/order.mocks.ts
- src/test/order_item_summary/OrderItemSummaryController.integration.test.ts
Resolves [BI-14018](https://companieshouse.atlassian.net/browse/BI-14018)
Adding on quantity field to summary page so it number of copies appears after user clicks onto a certificate's order summary. 
[BI-14018]: https://companieshouse.atlassian.net/browse/BI-14018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-14018-update email template and summary page to show quantites of copies

- terraform/groups/ecs-service/main.tf
At the moment the healthcheck works but is not being found when checking ECS, I believe it's because in the Terraform configuration for this project the `use_task_container_healthcheck` is not set to true.
https://github.com/companieshouse/terraform-modules/blob/main/aws/ecs/ecs-service/locals.tf#L55-L67
> CC-1534 - Fix unknown healthcheck terraform for orders-web

- src/app.ts
- src/controllers/basket.controller.ts
- src/controllers/order.confirmation.controller.ts
- src/test/__mocks__/redis.mocks.ts
- src/test/controllers/basket.controller.integration.test.ts
- src/test/controllers/order.confirmation.controller.integration.test.ts
- src/test/utils/redis.methods.utils.test.ts
- src/utils/redis.methods.ts
- src/utils/redisMethods.ts
Resolves [BI-14305](https://companieshouse.atlassian.net/browse/BI-14305) 
**Original PR**
See https://github.com/companieshouse/orders.web.ch.gov.uk/pull/265
**Issue** 
Testing in Staging found the payment reference ended up in some cases being `undefined` - possibly not being set properly  (it was stored in `req.session.extradata`) which caused error page as payment reference/response was be empty due the payments api not being able to be called. 
Bit of background- Payment reference is only able to be retrieved from the `createPayment` function in `basket-controller. `
However, the payment reference is needed to call `getPayment`  (via paymentAPI) in  the order-confirmation controller where the response is validated with the query params to display on the confirmation page. 
Thus, the …
> BI-14305- order confirmation payment reference fix
